"use client";

import { useMemo, useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, ChevronDown, ChevronRight, FileArchive, FileCode2, FileText, Folder, FolderOpen, Grid2X2, Image as ImageIcon, List, Music, MoreVertical, Play, Search, SlidersHorizontal, Trash2, Video, Link2, X, Copy, ExternalLink, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Input } from "@/components/ui/input";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { MediaLightbox } from "@/components/media/media-lightbox";
import type { MediaFile } from "@/components/media/media-card";
import { VideoThumbnail } from "@/components/media/video-thumbnail";
import { formatBytes, formatDate, isAudioMime, isVideoMime } from "@/lib/format";
import { cn } from "@/lib/utils";
import { useToast } from "@/hooks/use-toast";
import { NewFolderButton, FolderActions } from "@/components/folders/folder-actions";
import { BulkFolderActions } from "@/components/folders/bulk-folder-actions";
import { BulkFileActions } from "@/components/files/bulk-file-actions";
import { FOLDER_MIME_OPTIONS, FOLDER_SORT_OPTIONS, sortByMetadata, type FolderSortKey } from "@/lib/folder-sorting";

type FolderRow = { id:number; name:string; parentId:number|null; childFolderCount:number; fileCount:number; totalFileCount?:number; totalFolderCount?:number; totalSize?:number; createdAt?:string; updatedAt?:string; lastModified?:string };
type FileRow = MediaFile & { thumbnailPublicId?:string|null; status?:string; updatedAt?:string; lastModified?:string };
type ViewMode = "grid" | "list";
type FolderShareInfo = { id:number; createdAt:string; lastAccessedAt:string|null; url:string|null; recoverable:boolean };
type FolderShareStatus = { active:boolean; share:FolderShareInfo|null };

async function readShareApiResponse(response: Response): Promise<Record<string, unknown>> {
  const body = await response.text();
  let data: Record<string, unknown> = {};
  if (body.trim()) {
    try {
      const parsed: unknown = JSON.parse(body);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) data = parsed as Record<string, unknown>;
    } catch {
      // Next.js/proxy error pages may be HTML or an empty body. Surface HTTP status below.
    }
  }
  if (!response.ok) {
    const serverMessage = typeof data.message === "string" ? data.message : typeof data.error === "string" ? data.error : null;
    throw new Error(serverMessage ?? `Share request failed (HTTP ${response.status}). Please retry. If this continues, the server or database migration may need attention.`);
  }
  if (!body.trim() || Object.keys(data).length === 0) {
    throw new Error(`The server returned an empty or invalid response (HTTP ${response.status}). Please retry; if it continues, the share API needs server-side investigation.`);
  }
  return data;
}

function renderFileIcon(mime:string,className:string){
  if(mime.includes("pdf")) return <FileText className={className}/>;
  if(mime.includes("zip")||mime.includes("archive")||mime.includes("compressed")) return <FileArchive className={className}/>;
  if(mime.includes("javascript")||mime.includes("typescript")||mime.includes("json")||mime.includes("xml")||mime.includes("css")||mime.includes("html")) return <FileCode2 className={className}/>;
  return <FileText className={className}/>;
}

function FolderCard({folder,onOpen,selected,onToggle}:{folder:FolderRow;onOpen:()=>void;selected:boolean;onToggle:()=>void}){
  return <div className={cn("clay-folder-card group card-interactive rounded-2xl border p-4 transition-all",selected?"border-primary bg-primary/5 ring-1 ring-primary/30":"border-border/70 hover:border-primary/40")}>
    <div className="mb-4 flex items-start justify-between gap-2">
      <div className="flex items-start gap-2"><Checkbox checked={selected} onCheckedChange={onToggle} aria-label={`Select folder ${folder.name}`}/><button onClick={onOpen} aria-label={`Open folder ${folder.name}`} className="clay-folder-icon rounded-xl p-3 text-primary transition-colors hover:bg-primary/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><FolderOpen className="h-7 w-7"/></button></div>
      <div className="flex items-center gap-1"><FolderActions itemType="folder" itemId={folder.id} itemName={folder.name}/><button onClick={onOpen} aria-label={`Open ${folder.name}`} className="rounded p-2 hover:bg-muted focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><ChevronRight className="h-4 w-4 text-muted-foreground"/></button></div>
    </div>
    <button onClick={onOpen} className="w-full text-left"><div className="truncate font-semibold" title={folder.name}>{folder.name}</div><div className="mt-1 text-xs text-muted-foreground">{folder.totalFileCount??folder.fileCount} files · {folder.totalFolderCount??folder.childFolderCount} folders</div><div className="mt-1 text-sm font-medium">{formatBytes(folder.totalSize??0)}</div>{folder.lastModified&&<div className="mt-2 text-[11px] text-muted-foreground">Updated {formatDate(folder.lastModified)}</div>}</button>
  </div>;
}

function FileCard({file,onOpen,selected,onToggle}:{file:FileRow;onOpen:()=>void;selected:boolean;onToggle:()=>void}){
  const isImage=file.mimeType.startsWith("image/"),isVideo=isVideoMime(file.mimeType),isAudio=isAudioMime(file.mimeType);
  return <div className={cn("clay-media-card group relative overflow-hidden rounded-2xl border transition-all",selected?"border-primary ring-2 ring-primary/30":"border-border/70 hover:border-primary/40")}>
    <div className="absolute left-2 top-2 z-10 rounded-md border bg-background/95 p-1 shadow-sm" onClick={e=>e.stopPropagation()}><Checkbox checked={selected} onCheckedChange={onToggle} disabled={!!file.status&&file.status!=="active"} aria-label={`Select file ${file.originalName}`} /></div>
    <button onClick={onOpen} className="block w-full text-left"><div className="media-card__canvas aspect-square bg-muted/30">
      {isImage?<img src={file.publicUrl} alt={file.originalName} loading="lazy" className="h-full w-full object-cover"/>:isVideo?<div className="relative h-full w-full"><VideoThumbnail src={file.publicUrl} alt={file.originalName} className="h-full w-full object-cover" previewUrl={file.previewUrl} previewStatus={file.previewStatus} fallback={<div className="flex h-full w-full items-center justify-center"><Video className="h-12 w-12 text-muted-foreground/50"/></div>}/><span className="absolute bottom-3 left-3 rounded-full bg-black/70 px-2 py-1 text-[10px] text-white"><Play className="mr-1 inline h-3 w-3 fill-current"/>VIDEO</span></div>:isAudio?<div className="flex h-full items-center justify-center text-muted-foreground"><Music className="h-12 w-12"/></div>:<div className="flex h-full flex-col items-center justify-center gap-2 text-muted-foreground">{renderFileIcon(file.mimeType,"h-12 w-12")}<span className="max-w-[80%] truncate text-xs">{file.mimeType.split("/").pop()}</span></div>}
    </div><div className="media-card__metadata p-3"><div className="truncate text-sm font-medium" title={file.originalName}>{file.originalName}</div><div className="mt-1 text-xs text-muted-foreground">{formatBytes(file.size)} · Updated {formatDate(file.updatedAt??file.createdAt)}</div></div></button>
    <div className="flex justify-end border-t px-2 py-1"><FolderActions itemType="file" itemId={file.id} itemName={file.originalName} fileUrl={file.publicUrl}/></div>
  </div>;
}

export default function FolderBrowser(){
  const {toast}=useToast();
  const router=useRouter(),params=useSearchParams(),folderId=Number(params.get("folderId"))||null;
  const initialSort = params.get("sort");
  const sort: FolderSortKey = FOLDER_SORT_OPTIONS.some(option=>option.value===initialSort)?initialSort as FolderSortKey:"created:desc";
  const status = params.get("status") ?? "active";
  const mimeType = params.get("mimeType") ?? "all";
  const from = params.get("from") ?? "";
  const to = params.get("to") ?? "";
  const [search,setSearch]=useState(""),[view,setView]=useState<ViewMode>("grid"),[openFile,setOpenFile]=useState<FileRow|null>(null),[shareBusy,setShareBusy]=useState(false),[shareDialogOpen,setShareDialogOpen]=useState(false),[shareInfo,setShareInfo]=useState<FolderShareStatus|null>(null),[shareLoading,setShareLoading]=useState(false),[shareError,setShareError]=useState(""),[revokeShareOpen,setRevokeShareOpen]=useState(false),[deleteBusy,setDeleteBusy]=useState(false),[deleteDialogOpen,setDeleteDialogOpen]=useState(false),[deleteError,setDeleteError]=useState(""),[filtersOpen,setFiltersOpen]=useState(false),[selectedFiles,setSelectedFiles]=useState<Set<number>>(new Set()),[selectedFolders,setSelectedFolders]=useState<Set<number>>(new Set()),[bulkDeleteOpen,setBulkDeleteOpen]=useState(false),[bulkDeleteBusy,setBulkDeleteBusy]=useState(false);
  const foldersQuery=useQuery<FolderRow[]>({queryKey:["folder-browser","folders"],queryFn:async()=>{const r=await fetch("/api/folders?all=true");if(!r.ok)throw Error("Failed to load folders");return(await r.json()).folders??[];}});
  const current=foldersQuery.data?.find(f=>f.id===folderId)??null;
  const invalidDateRange=Boolean(from&&to&&from>to);
  const childFolders=useMemo(()=>sortByMetadata((foldersQuery.data??[]).filter(f=>f.parentId===folderId).filter(f=>f.name.toLocaleLowerCase().includes(search.trim().toLocaleLowerCase())).filter(f=>!from||!!f.createdAt&&new Date(f.createdAt)>=new Date(`${from}T00:00:00.000Z`)).filter(f=>!to||!!f.createdAt&&new Date(f.createdAt)<=new Date(`${to}T23:59:59.999Z`)),sort),[foldersQuery.data,folderId,search,sort,from,to]);
  const filesQuery=useQuery<{files:FileRow[];total:number}>({queryKey:["folder-browser","files",folderId,status,mimeType,from,to],enabled:folderId!==null&&!invalidDateRange,queryFn:async()=>{
    const limit=100;
    const fetchPage=async(page:number)=>{const query=new URLSearchParams({folderId:String(folderId),status,sort:"created",order:"desc",page:String(page),limit:String(limit)});if(mimeType!=="all")query.set("mimeType",mimeType);if(from)query.set("from",from);if(to)query.set("to",to);const r=await fetch(`/api/files?${query}`,{cache:"no-store"});if(!r.ok)throw Error("Failed to load folder files");return (await r.json()) as {files:FileRow[];total:number;page:number;limit:number};};
    const first=await fetchPage(1);
    const totalPages=Math.ceil(first.total/limit);
    if(totalPages<=1)return first;
    const rest=await Promise.all(Array.from({length:totalPages-1},(_,i)=>fetchPage(i+2)));
    return {...first,files:[...first.files,...rest.flatMap(page=>page.files)]};
  }});
  const files=useMemo(()=>sortByMetadata((filesQuery.data?.files??[]).filter(f=>f.originalName.toLowerCase().includes(search.toLowerCase())),sort),[filesQuery.data?.files,search,sort]);
  const visibleMedia=files.filter(f=>f.mimeType.startsWith("image/")||isVideoMime(f.mimeType)||isAudioMime(f.mimeType));
  const eligibleFiles=files.filter(file=>!file.status||file.status==="active");
  const currentFileIds=eligibleFiles.map(f=>f.id);
  const currentFolderIds=childFolders.map(f=>f.id);
  const allCurrentFoldersSelected=currentFolderIds.length>0&&currentFolderIds.every(id=>selectedFolders.has(id));
  const someCurrentFoldersSelected=currentFolderIds.some(id=>selectedFolders.has(id));
  const toggleFolderSelection=(id:number)=>setSelectedFolders(previous=>{const next=new Set(previous);if(next.has(id))next.delete(id);else next.add(id);return next;});
  const toggleSelectAllFolders=()=>setSelectedFolders(previous=>{const next=new Set(previous);if(allCurrentFoldersSelected)currentFolderIds.forEach(id=>next.delete(id));else currentFolderIds.forEach(id=>next.add(id));return next;});
  const allCurrentFilesSelected=currentFileIds.length>0&&currentFileIds.every(id=>selectedFiles.has(id));
  const someCurrentFilesSelected=currentFileIds.some(id=>selectedFiles.has(id));
  const toggleFileSelection=(id:number)=>setSelectedFiles(previous=>{const next=new Set(previous);if(next.has(id))next.delete(id);else next.add(id);return next;});
  const toggleSelectAllFiles=()=>setSelectedFiles(previous=>{const next=new Set(previous);if(allCurrentFilesSelected)currentFileIds.forEach(id=>next.delete(id));else currentFileIds.forEach(id=>next.add(id));return next;});
  const deleteSelectedFiles=async()=>{if(bulkDeleteBusy||selectedFiles.size===0)return;const ids=Array.from(selectedFiles);if(ids.length>5000){toast({title:"Too many files selected",description:"Select no more than 5,000 files per delete operation.",variant:"destructive"});return;}setBulkDeleteBusy(true);try{const response=await fetch("/api/files/bulk-delete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ids})});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result.detail||result.error||`Bulk delete failed (HTTP ${response.status}).`);const deleted:number[]=Array.isArray(result.deleted)?result.deleted:[];const failed:{id:number;error:string}[]=Array.isArray(result.failed)?result.failed:[];setSelectedFiles(new Set(failed.map(item=>item.id)));setBulkDeleteOpen(false);await Promise.all([filesQuery.refetch(),foldersQuery.refetch()]);toast({title:failed.length?`${deleted.length} deleted, ${failed.length} failed`:`${deleted.length} files deleted`,description:failed.length?"Some files could not be deleted. Failed files remain selected.":"Files were marked deleted using the existing deletion rules.",variant:failed.length?"destructive":"default"});}catch(error){toast({title:"Bulk delete failed",description:error instanceof Error?error.message:"Could not delete selected files.",variant:"destructive"});}finally{setBulkDeleteBusy(false);}};
  const path=useMemo(()=>{const map=new Map((foldersQuery.data??[]).map(f=>[f.id,f]));const out:FolderRow[]=[];let id=folderId;const seen=new Set<number>();while(id&& !seen.has(id)){seen.add(id);const f=map.get(id);if(!f)break;out.unshift(f);id=f.parentId;}return out;},[foldersQuery.data,folderId]);
  const go=(id:number|null)=>{setSelectedFiles(new Set());setSelectedFolders(new Set());const next=new URLSearchParams(params.toString());if(id)next.set("folderId",String(id));else next.delete("folderId");router.push(`/folders${next.size?`?${next.toString()}`:""}`);};
  const changeFilter=(key:string,value:string)=>{setSelectedFiles(new Set());setSelectedFolders(new Set());const next=new URLSearchParams(params.toString());if(key==="status")next.set(key,value);else if(value&&value!=="all")next.set(key,value);else next.delete(key);router.replace(`/folders?${next.toString()}`,{scroll:false});};
  const hasActiveFilters=mimeType!=="all"||status!=="active"||Boolean(from||to);
  const clearFilters=()=>{setSelectedFiles(new Set());setSelectedFolders(new Set());setSearch("");const next=new URLSearchParams(params.toString());["status","mimeType","from","to"].forEach(key=>next.delete(key));router.replace(`/folders?${next.toString()}`,{scroll:false});};
  const loadShareStatus=async(folderId:number)=>{setShareLoading(true);setShareError("");try{const r=await fetch(`/api/folders/${folderId}/share`,{cache:"no-store"});const j=await readShareApiResponse(r);if(typeof j.active!=="boolean"||!(j.share===null||(j.share&&typeof j.share==="object")))throw Error("The share API returned an unexpected response shape.");setShareInfo(j as unknown as FolderShareStatus);}catch(e){setShareError(e instanceof Error?e.message:"Could not load share link status")}finally{setShareLoading(false)}};
  const openShareManager=()=>{if(!current)return;setShareDialogOpen(true);setShareInfo(null);void loadShareStatus(current.id)};
  const copyShareLink=async(url:string)=>{try{await navigator.clipboard.writeText(url);toast({title:"Share link copied",description:"Anyone with this link can access the shared folder."});}catch{toast({title:"Could not copy automatically",description:"Select and copy the share URL manually.",variant:"destructive"});}};
  const createShareLink=async()=>{if(!current||shareBusy)return;setShareBusy(true);setShareError("");try{const r=await fetch(`/api/folders/${current.id}/share`,{method:"POST"});const j=await readShareApiResponse(r);if(typeof j.url!=="string"||typeof j.shareId!=="number")throw Error("The server did not return a valid share URL.");setShareInfo({active:true,share:{id:j.shareId,createdAt:typeof j.createdAt==="string"?j.createdAt:new Date().toISOString(),lastAccessedAt:null,url:j.url,recoverable:true}});try{await navigator.clipboard.writeText(j.url);toast({title:"Share link created and copied"});}catch{toast({title:"Share link created",description:"Copy it using the Copy link button."});}}catch(e){setShareError(e instanceof Error?e.message:"Failed to generate share link")}finally{setShareBusy(false)}};
  const revokeShare=async()=>{if(!current||!shareInfo?.share||shareBusy)return;setShareBusy(true);setShareError("");try{const r=await fetch(`/api/folders/${current.id}/share/${shareInfo.share.id}`,{method:"DELETE"});await readShareApiResponse(r);setShareInfo({active:false,share:null});setRevokeShareOpen(false);toast({title:"Share link revoked",description:"The link no longer grants access. The folder and its files are unchanged."});}catch(e){setShareError(e instanceof Error?e.message:"Failed to revoke share link")}finally{setShareBusy(false)}};
  const deleteCurrent=async()=>{if(!current||deleteBusy)return;setDeleteBusy(true);setDeleteError("");try{const r=await fetch(`/api/folders/${current.id}`,{method:"DELETE"});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.detail||j.error||"Failed to delete folder");await foldersQuery.refetch();setDeleteDialogOpen(false);if(Array.isArray(j.telegramErrors)&&j.telegramErrors.length){toast({title:"Folder removed with warnings",description:"The folder was removed, but some storage objects may require cleanup.",variant:"destructive"});}else{toast({title:"Folder deleted",description:`${j.deletedFolders??1} folder(s) removed; ${j.deletedFiles??0} file(s) marked deleted.`});}go(current.parentId);}catch(e){setDeleteError(e instanceof Error?e.message:"Failed to delete folder")}finally{setDeleteBusy(false)}};
  const loading=foldersQuery.isLoading||(folderId!==null&&filesQuery.isLoading);
  return <div className="page-workspace min-w-0 space-y-5">
    <section className="space-y-4">
      <div className="flex min-w-0 flex-wrap items-center gap-x-3 gap-y-2 text-sm text-muted-foreground">
        {folderId!==null&&<Button variant="ghost" size="sm" className="-ml-2 shrink-0" onClick={()=>go(current?.parentId??path.at(-2)?.id??null)}><ArrowLeft className="mr-2 h-4 w-4"/>Back to parent</Button>}
        <nav aria-label="Breadcrumb" className="flex min-w-0 flex-wrap items-center gap-2"><button onClick={()=>go(null)} className="rounded-sm hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">My Storage</button>{path.map(f=><span key={f.id} className="flex min-w-0 items-center gap-2"><ChevronRight className="h-3 w-3 shrink-0"/><button onClick={()=>go(f.id)} aria-current={f.id===folderId?"page":undefined} className="max-w-40 truncate rounded-sm hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">{f.name}</button></span>)}</nav>
      </div>
      <div className="clay-panel flex min-w-0 flex-col gap-4 p-4 md:p-5 lg:flex-row lg:items-center lg:justify-between">
        <div className="min-w-0 flex-1"><div className="flex items-center gap-3"><div className="clay-folder-icon flex h-11 w-11 shrink-0 items-center justify-center rounded-xl text-primary"><FolderOpen className="h-6 w-6"/></div><div className="min-w-0"><h1 className="type-h1 truncate">{current?.name??"My Storage"}</h1><p className="mt-1 text-sm text-muted-foreground">{current?`${current.totalFileCount??current.fileCount} files · ${current.totalFolderCount??current.childFolderCount} folders · ${formatBytes(current.totalSize??0)}`:"Organize and manage your folders and files."}</p></div></div></div>
        <div className="flex min-w-0 flex-wrap items-center gap-2 [&>button]:min-h-11 [&>button]:flex-1 sm:[&>button]:flex-none lg:justify-end">
          <NewFolderButton parentId={folderId}/>
          <Button variant="outline" onClick={()=>router.push(current?`/upload?folderId=${current.id}`:"/upload")}><Folder className="mr-2 h-4 w-4"/>Upload Files</Button>
          <Button variant="outline" onClick={()=>router.push(folderId!==null?`/folders?upload=1&parentFolderId=${folderId}`:"/folders?upload=1")}><FolderOpen className="mr-2 h-4 w-4"/>Upload Folder</Button>
          {current&&<DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="icon" aria-label="More folder actions"><MoreVertical className="h-4 w-4"/></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-52"><DropdownMenuItem onSelect={openShareManager}><Link2 className="h-4 w-4"/>Manage share link…</DropdownMenuItem><DropdownMenuSeparator/><DropdownMenuItem className="text-destructive focus:text-destructive" onSelect={()=>{setDeleteError("");setDeleteDialogOpen(true);}}><Trash2 className="h-4 w-4"/>Delete folder…</DropdownMenuItem></DropdownMenuContent></DropdownMenu>}
        </div>
      </div>
    </section>
    <section className="clay-toolbar min-w-0 space-y-3 p-3 sm:p-4" aria-label="Folder and file filters">
      <div className="flex min-w-0 flex-col gap-3 lg:flex-row lg:items-center">
        <div className="relative min-w-0 flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input value={search} onChange={e=>{setSelectedFiles(new Set());setSearch(e.target.value);}} placeholder={`Search ${current?"this folder":"folders"}...`} className={cn("pl-9",search&&"pr-10")} aria-label="Search folders and files"/>{search&&<button type="button" aria-label="Clear search" onClick={()=>{setSelectedFiles(new Set());setSearch("");}} className="absolute right-2 top-1.5 rounded-md p-1.5 text-muted-foreground hover:bg-muted hover:text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><X className="h-4 w-4"/></button>}</div>
        <div className="grid min-w-0 grid-cols-2 gap-2 sm:flex sm:flex-wrap sm:items-center [&_label]:min-w-0 [&_select]:w-full [&_select]:text-ellipsis">
          <label className="flex min-w-0 items-center gap-2 text-xs text-muted-foreground">Status<select aria-label="Status filter" value={status} onChange={e=>changeFilter("status",e.target.value)} className={cn("h-10 min-w-0 rounded-md border border-input bg-background px-2 text-sm text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",status!=="active"&&"border-primary/60 bg-primary/5")}><option value="active">Active</option><option value="deleted">Deleted</option><option value="missing">Missing</option><option value="all">All</option></select></label>
          <label className="flex min-w-0 items-center gap-2 text-xs text-muted-foreground">Sort by<select aria-label="Sort folders and files" value={sort} onChange={e=>changeFilter("sort",e.target.value)} className="h-10 min-w-0 max-w-full rounded-md border border-input bg-background px-2 text-sm text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring">{FOLDER_SORT_OPTIONS.map(option=><option key={option.value} value={option.value}>{option.value==="created:desc"?"Newest first":option.value==="created:asc"?"Oldest first":option.value==="name:asc"?"Name A → Z":option.value==="name:desc"?"Name Z → A":option.label}</option>)}</select></label>
          <div className="col-span-2 flex items-center justify-between gap-3 sm:col-span-1"><div className="flex shrink-0 rounded-lg border p-1" role="group" aria-label="Content view"><Button variant={view==="grid"?"secondary":"ghost"} size="sm" aria-label="Grid view" aria-pressed={view==="grid"} onClick={()=>setView("grid")}><Grid2X2 className="h-4 w-4"/></Button><Button variant={view==="list"?"secondary":"ghost"} size="sm" aria-label="List view" aria-pressed={view==="list"} onClick={()=>setView("list")}><List className="h-4 w-4"/></Button></div><Button type="button" variant="outline" size="sm" className="md:hidden" aria-expanded={filtersOpen} aria-controls="folder-extra-filters" onClick={()=>setFiltersOpen(value=>!value)}><SlidersHorizontal className="mr-2 h-4 w-4"/>Filters<ChevronDown className={cn("ml-2 h-4 w-4 transition-transform",filtersOpen&&"rotate-180")}/></Button></div>
        </div>
      </div>
      <div id="folder-extra-filters" className={cn("space-y-3 border-t border-border/60 pt-3 md:block",!filtersOpen&&"hidden")}>
        <div className="flex flex-wrap items-center gap-2" aria-label="File type filter">{FOLDER_MIME_OPTIONS.map(option=><button key={option.value} type="button" aria-pressed={mimeType===option.value} onClick={()=>changeFilter("mimeType",option.value)} className={cn("rounded-full border px-3 py-1.5 text-xs font-medium transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",mimeType===option.value?"border-primary/40 bg-primary/12 text-primary":"border-border bg-background text-muted-foreground hover:bg-muted hover:text-foreground")}>{option.label}</button>)}</div>
        <div className="grid min-w-0 grid-cols-2 items-end gap-3 sm:flex sm:flex-wrap"><label className="flex min-w-0 flex-col gap-1 text-xs text-muted-foreground">From<Input type="date" aria-label="From date" value={from} max={to||undefined} onChange={e=>changeFilter("from",e.target.value)} className="h-10 w-full min-w-0 sm:w-[145px]"/></label><label className="flex min-w-0 flex-col gap-1 text-xs text-muted-foreground">To<Input type="date" aria-label="To date" value={to} min={from||undefined} onChange={e=>changeFilter("to",e.target.value)} className="h-10 w-full min-w-0 sm:w-[145px]"/></label><div className="col-span-2 ml-auto flex min-w-0 flex-wrap items-center justify-end gap-2 sm:col-span-1">{hasActiveFilters&&<Button variant="ghost" size="sm" onClick={clearFilters} className="h-9"><X className="mr-1 h-3.5 w-3.5"/>Clear filters</Button>}<span className="text-xs text-muted-foreground">{current?`${files.length} matching files`:`${childFolders.length} matching folders`}</span></div></div>
        {from&&to&&from>to&&<p role="alert" className="text-sm text-destructive">The start date must be on or before the end date.</p>}
      </div>
    </section>
    {invalidDateRange?<div role="alert" className="rounded-xl border border-destructive/30 bg-destructive/5 p-5 text-sm text-destructive">The start date must be on or before the end date. Adjust the date range or clear filters.</div>:loading?<div className="rounded-2xl border p-12 text-center text-sm text-muted-foreground">Loading storage...</div>:foldersQuery.isError||(folderId!==null&&filesQuery.isError)?<div role="alert" className="rounded-xl border border-destructive/30 p-8 text-center"><p className="font-medium">Could not load this folder.</p><p className="mt-1 text-sm text-muted-foreground">Check your connection and try again.</p><Button variant="outline" className="mt-4" onClick={()=>{void foldersQuery.refetch();if(folderId!==null)void filesQuery.refetch();}}>Retry</Button></div>:<>
      {childFolders.length>0&&<section className="space-y-3"><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">Folders <span className="normal-case tracking-normal">({childFolders.length})</span></h2><div className="clay-status-panel flex flex-wrap items-center gap-3 p-2"><label className="flex min-h-9 cursor-pointer items-center gap-2 text-sm"><Checkbox checked={allCurrentFoldersSelected?true:someCurrentFoldersSelected?"indeterminate":false} onCheckedChange={toggleSelectAllFolders} aria-label="Select all matching folders in this view"/><span>Select all folders</span></label>{selectedFolders.size>0&&<><span className="text-xs text-muted-foreground">{selectedFolders.size} folders selected</span><BulkFolderActions selectedIds={Array.from(selectedFolders)} folders={foldersQuery.data??[]} onSelectionChange={ids=>setSelectedFolders(new Set(ids))}/><Button size="sm" variant="ghost" onClick={()=>setSelectedFolders(new Set())}>Clear selection</Button></>}</div></div>{view==="grid"?<div className="grid min-w-0 grid-cols-1 gap-3 min-[360px]:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">{childFolders.map(f=><FolderCard key={f.id} folder={f} onOpen={()=>go(f.id)} selected={selectedFolders.has(f.id)} onToggle={()=>toggleFolderSelection(f.id)}/>)}</div>:<div className="space-y-2">{childFolders.map(f=><div key={f.id} className={cn("flex min-w-0 items-center gap-3 rounded-xl border p-3 transition-colors hover:bg-muted/30",selectedFolders.has(f.id)&&"border-primary bg-primary/5")}><Checkbox checked={selectedFolders.has(f.id)} onCheckedChange={()=>toggleFolderSelection(f.id)} aria-label={`Select folder ${f.name}`}/><button onClick={()=>go(f.id)} className="flex min-w-0 flex-1 items-center gap-3 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><Folder className="h-5 w-5 shrink-0 text-primary"/><span className="min-w-0 flex-1 truncate" title={f.name}>{f.name}</span><span className="hidden shrink-0 text-xs text-muted-foreground sm:inline">{f.totalFileCount??f.fileCount} files · {f.totalFolderCount??f.childFolderCount} folders · {formatBytes(f.totalSize??0)}</span>{f.lastModified&&<span className="hidden shrink-0 text-xs text-muted-foreground lg:inline">Updated {formatDate(f.lastModified)}</span>}</button><FolderActions itemType="folder" itemId={f.id} itemName={f.name}/></div>)}</div>}</section>}
      {folderId!==null&&files.length>0&&<section className="space-y-3"><div className="flex min-w-0 flex-wrap items-center justify-between gap-3"><h2 className="text-sm font-semibold uppercase tracking-wide text-muted-foreground">Files <span className="normal-case tracking-normal">({files.length})</span></h2><div className="clay-status-panel flex min-w-0 flex-wrap items-center gap-3 p-2 sm:p-2.5"><label className="flex min-h-9 cursor-pointer items-center gap-2 text-sm"><Checkbox checked={allCurrentFilesSelected?true:someCurrentFilesSelected?"indeterminate":false} onCheckedChange={toggleSelectAllFiles} aria-label="Select all matching files in this folder across all loaded pages"/><span>Select all files</span></label>{selectedFiles.size>0&&<><span className="text-xs text-muted-foreground">{selectedFiles.size} selected</span><BulkFileActions selectedIds={Array.from(selectedFiles)} onSelectionChange={ids=>setSelectedFiles(new Set(ids))}/><Button size="sm" variant="destructive" disabled={bulkDeleteBusy} onClick={()=>setBulkDeleteOpen(true)}><Trash2 className="mr-1 h-4 w-4"/>Delete</Button><Button size="sm" variant="ghost" onClick={()=>setSelectedFiles(new Set())} disabled={bulkDeleteBusy}>Clear selection</Button></>}</div></div>{view==="grid"?<div className="grid min-w-0 grid-cols-1 gap-3 min-[360px]:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6">{files.map(f=><FileCard key={f.id} file={f} onOpen={()=>setOpenFile(f)} selected={selectedFiles.has(f.id)} onToggle={()=>toggleFileSelection(f.id)}/>)}</div>:<div className="divide-y rounded-xl border">{files.map(f=><div key={f.id} className={cn("flex min-w-0 items-center gap-3 p-3 transition-colors hover:bg-muted/40",selectedFiles.has(f.id)&&"bg-primary/5")}><Checkbox checked={selectedFiles.has(f.id)} onCheckedChange={()=>toggleFileSelection(f.id)} disabled={!!f.status&&f.status!=="active"} aria-label={`Select file ${f.originalName}`}/><button onClick={()=>setOpenFile(f)} className="flex min-w-0 flex-1 items-center gap-3 text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><div className="flex h-10 w-10 items-center justify-center rounded-lg bg-muted">{f.mimeType.startsWith("image/")?<ImageIcon className="h-5 w-5"/>:f.mimeType.startsWith("audio/")?<Music className="h-5 w-5"/>:<FileText className="h-5 w-5"/>}</div><span className="min-w-0 flex-1 truncate text-sm" title={f.originalName}>{f.originalName}</span><span className="hidden shrink-0 text-xs text-muted-foreground sm:inline">{f.mimeType.split("/").pop()}</span><span className="shrink-0 text-right text-xs text-muted-foreground">{formatBytes(f.size)}</span><span className="hidden w-28 shrink-0 text-right text-xs text-muted-foreground lg:inline">Updated {formatDate(f.updatedAt??f.createdAt)}</span></button><FolderActions itemType="file" itemId={f.id} itemName={f.originalName}/></div>)}</div>}</section>}
      {folderId!==null&&!childFolders.length&&!files.length&&<div className="rounded-2xl border p-12 text-center"><Folder className="mx-auto h-12 w-12 text-muted-foreground/40"/><h3 className="mt-3 font-medium">{hasActiveFilters||search?"No matching items":"This folder is empty"}</h3><p className="mt-1 text-sm text-muted-foreground">{hasActiveFilters||search?"Try changing your search or filters.":"Upload files or create a folder to get started."}</p>{(hasActiveFilters||search)&&<Button variant="outline" className="mt-4" onClick={()=>{setSearch("");clearFilters();}}>Clear search and filters</Button>}</div>}
      {folderId===null&&!childFolders.length&&<div className="rounded-2xl border p-12 text-center"><Folder className="mx-auto h-12 w-12 text-muted-foreground/40"/><h3 className="mt-3 font-medium">No folders yet</h3><p className="mt-1 text-sm text-muted-foreground">Create your first folder above.</p></div>}
    </>}
    <Dialog open={bulkDeleteOpen} onOpenChange={value=>{if(!bulkDeleteBusy)setBulkDeleteOpen(value);}}>
      <DialogContent className="w-[calc(100%-1rem)] max-w-lg">
        <DialogHeader><DialogTitle>Delete {selectedFiles.size} selected files?</DialogTitle><DialogDescription>This uses the existing bulk-delete behavior: selected files are marked deleted and their public URLs stop working. This does not delete the containing folder or unselected files.</DialogDescription></DialogHeader>
        <div className="max-h-48 overflow-y-auto rounded-lg border p-3 text-sm"><ul className="space-y-1">{files.filter(file=>selectedFiles.has(file.id)).slice(0,20).map(file=><li key={file.id} className="truncate">{file.originalName}</li>)}</ul>{selectedFiles.size>20&&<p className="mt-2 text-xs text-muted-foreground">and {selectedFiles.size-20} more…</p>}</div>
        <DialogFooter><Button variant="outline" disabled={bulkDeleteBusy} onClick={()=>setBulkDeleteOpen(false)}>Cancel</Button><Button variant="destructive" disabled={bulkDeleteBusy||selectedFiles.size===0} onClick={()=>void deleteSelectedFiles()}>{bulkDeleteBusy?"Deleting…":`Delete ${selectedFiles.size} files`}</Button></DialogFooter>
      </DialogContent>
    </Dialog>
    <Dialog open={shareDialogOpen} onOpenChange={value=>{if(!shareBusy){setShareDialogOpen(value);if(!value)setRevokeShareOpen(false);}}}>
      <DialogContent className="max-h-[85vh] overflow-y-auto sm:max-w-xl">
        <DialogHeader><DialogTitle>{revokeShareOpen?"Revoke folder share link?":"Manage folder share link"}</DialogTitle><DialogDescription>{revokeShareOpen?"Anyone using this link will lose access through it. The folder and its files will remain unchanged.":`Manage public access to “${current?.name??"this folder"}”. Anyone with an active share link may view and download its active files.`}</DialogDescription></DialogHeader>
        {revokeShareOpen? <div className="space-y-4"><div className="rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm"><p className="font-medium">The share link will stop working immediately.</p><p className="mt-1 text-muted-foreground">This does not delete the folder, nested folders, or files.</p></div><DialogFooter><Button variant="outline" disabled={shareBusy} onClick={()=>setRevokeShareOpen(false)}>Cancel</Button><Button variant="destructive" disabled={shareBusy} onClick={()=>void revokeShare()}><Trash2 className="mr-2 h-4 w-4"/>{shareBusy?"Revoking…":"Revoke link"}</Button></DialogFooter></div> : <div className="space-y-4">
          {shareLoading&&<p className="py-5 text-sm text-muted-foreground">Checking share status…</p>}
          {!shareLoading&&shareError&&<div role="alert" className="rounded-lg border border-destructive/30 bg-destructive/5 p-3 text-sm text-destructive">{shareError}<Button variant="outline" size="sm" className="ml-3" onClick={()=>current&&void loadShareStatus(current.id)}>Retry</Button></div>}
          {!shareLoading&&shareInfo?.active&&shareInfo.share&&<div className="space-y-3 rounded-xl border p-4">
            <div className="flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-status-completed"/><span className="font-medium">Share link active</span><span className="ml-auto rounded-full bg-status-completed/10 px-2 py-1 text-xs text-status-completed">Active</span></div>
            <p className="text-xs text-muted-foreground">Created {formatDate(shareInfo.share.createdAt)}{shareInfo.share.lastAccessedAt?` · Last accessed ${formatDate(shareInfo.share.lastAccessedAt)}`:" · Not accessed yet"}</p>
            {shareInfo.share.url?<><label className="block text-sm font-medium" htmlFor="folder-share-url">Share URL</label><Input id="folder-share-url" readOnly value={shareInfo.share.url} className="font-mono text-xs"/><div className="flex flex-wrap gap-2"><Button onClick={()=>void copyShareLink(shareInfo.share!.url!)}><Copy className="mr-2 h-4 w-4"/>Copy link</Button><Button variant="outline" onClick={()=>window.open(shareInfo.share!.url!,"_blank","noopener,noreferrer")}><ExternalLink className="mr-2 h-4 w-4"/>Open link</Button></div></>:<p className="rounded-lg border border-amber-500/30 bg-amber-500/5 p-3 text-sm text-muted-foreground">{shareInfo.share.recoverable?"The saved link token is available, but the public share URL could not be built. Check the SHARE_PUBLIC_URL configuration and retry.":"This link was created before secure link recovery was added, so its URL cannot be displayed again. Revoke this link, then create a new one."}</p>}
            <div className="border-t pt-3"><Button variant="destructive" disabled={shareBusy} onClick={()=>setRevokeShareOpen(true)}><Trash2 className="mr-2 h-4 w-4"/>Revoke link…</Button></div>
          </div>}
          {!shareLoading&&shareInfo&&!shareInfo.active&&<div className="rounded-xl border border-dashed p-5 text-center"><Link2 className="mx-auto h-8 w-8 text-muted-foreground"/><p className="mt-2 font-medium">No active share link</p><p className="mt-1 text-sm text-muted-foreground">Create a link to share this folder. You can revoke it any time.</p><Button className="mt-4" disabled={shareBusy} onClick={()=>void createShareLink()}><Link2 className="mr-2 h-4 w-4"/>{shareBusy?"Creating link…":"Generate share link"}</Button></div>}
          <DialogFooter><Button variant="outline" disabled={shareBusy} onClick={()=>setShareDialogOpen(false)}>Close</Button></DialogFooter>
        </div>}
      </DialogContent>
    </Dialog>
    <Dialog open={deleteDialogOpen} onOpenChange={value=>{if(!deleteBusy)setDeleteDialogOpen(value);}}>
      <DialogContent>
        <DialogHeader><DialogTitle>Delete “{current?.name}”?</DialogTitle><DialogDescription>This permanently removes the folder and its nested folder structure. Files inside will be marked deleted and storage-provider deletion is best-effort. The folder structure cannot be restored from this action.</DialogDescription></DialogHeader>
        <div className="rounded-lg border border-destructive/20 bg-destructive/5 p-3 text-sm"><p className="font-medium">You are deleting: {current?.name}</p><p className="mt-1 text-muted-foreground">{current?.totalFolderCount??current?.childFolderCount??0} nested folders · {current?.totalFileCount??current?.fileCount??0} files · {formatBytes(current?.totalSize??0)}</p></div>
        {deleteError&&<p role="alert" className="text-sm text-destructive">{deleteError}</p>}
        <DialogFooter><Button variant="outline" disabled={deleteBusy} onClick={()=>setDeleteDialogOpen(false)}>Cancel</Button><Button variant="destructive" disabled={deleteBusy||!current} onClick={()=>void deleteCurrent()}>{deleteBusy?"Deleting…":"Delete folder"}</Button></DialogFooter>
      </DialogContent>
    </Dialog>
    <MediaLightbox file={openFile} siblings={visibleMedia.map(f=>f.id)} open={!!openFile} onClose={()=>setOpenFile(null)} onNavigate={id=>setOpenFile(visibleMedia.find(f=>f.id===id)??null)}/>
  </div>;
}
